### PR TITLE
[gentoo-tree-sync] Resurrect + add support for keeping a backup in sync (fixes #24)

### LINKED ISSUE #24: [gentoo-tree-sync] Idea: Also handle the "old portdir" sync
**Requirement**
In order for `gentoo-tree-diff` to work, you need an old and a new portdir. The obvious way to handle this, is to do something like this:
```
rm -rf portdir-old
mv portdir portdir-old
mkdir portdir
gentoo-tree-sync portdir
gentoo-tree-diff portdir-old portdir
```

The problem with this way, is that the first command (`rm -rf portdir-old`) will fail because the permissions of the files in that directory are set in such a way that the user running this script, cannot delete them. In fact, the content of `portdir` is owned by root (as set by the container that is executed by the `gentoo-tree-sync` command).

As I don't want the "portage user" on my machine to have sudo rights, there is no way for that user to delete the old portdir. It would be interesting if `binary-gentoo` offers a nice way to handle this, because keeping an old and a new portdir is needed for it to work.

**Proposal for solution**
The maintenance of the old portdir could be taken care of by `gentoo-tree-sync`. Something like `gentoo-tree-sync --old-portdir portdir-old portdir`, which would then do the following:
* delete the contents of the directory specified by `--old-portdir`
* move the contents of `portdir` to the directory specified by `--old-portdir`
* sync the portage tree to `portdir` (existing functionality)

If you have other ideas, let me know. If you agree that this should be solved by `binary-gentoo` and when agreed upon a solution, I can see if I can implement this.

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #24

CC @vojeroen

### CODE REVIEW

**Comment by vojeroen** [comment]
I will have a look at this later, but it may take a few days. Thanks for the effort already :)

**Comment by hartwork** [comment]
@vojeroen maybe let me add a note with regard to the big picture here:

`gentoo-tree-sync` could theoretically make binary-gentoo a more complete solution to some (future) users, be a place where we keep adjusting things to provide sync with best security out of the box, and — if it fits your use case — be the tool that you use to sync the tree. If it doesn't fit your case, then it would have no current user and then the question is if the distance is small and of enough value to get to zero or if your current custom approach works better for you, even midterm. If that's the case let's be realistic and not resurrect the tool due to zeor known users then (in the spirit of [not riding a dead horse any further](https://blog.itil.org/2012/12/when-you-discover-youre-riding-a-dead-horse-the-best-strategy-is-to-dismount/)). Please let me know how you feel about that.

**Comment by vojeroen** [comment]
@hartwork I have had a look at the new `gentoo-tree-sync` and it does indeed fit my use case. It basically allows me to run a small script regularly to build new packages:

```
gentoo-tree-sync --backup-to portdir-old portdir
gentoo-tree-diff --keywords amd64 ~/portdir-old ~/portdir > ~/tree-diff
<glue script to compare installed packages with ~/tree-diff and build upgraded packages>
```

This is slightly more convenient than what I am doing now (as explained in https://github.com/hartwork/binary-gentoo/issues/24#issuecomment-892022009), so I wouldn't mind having this tool. I leave it up to you if you want to include it again, but if you do, I'll definitely use it.

**Comment by hartwork** [comment]
> I leave it up to you if you want to include it again, but if you do, I'll definitely use it.

@vojeroen okay nice, let's bring it back then.

**Comment by hartwork** [comment]
PS: Now included in PyPI release 6.1.0

**Comment by vojeroen** [comment]
Running back on the PyPI release instead of straight from the repo. Works like a charm :)

**Comment by hartwork** [comment]
Cool!

**Pull request merged**
